In [18]:
import numpy as np
from scipy import linalg, special, sparse
from scipy.linalg import eig

In [4]:
# problem 1 
arr = np.ones((4, 4))
np.savetxt('test.text', arr)
data = np.loadtxt('test.text')
print(data)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
# problem 2 
values = [27, 64, 891]
cubic_roots = special.cbrt(values)
for value in cubic_roots:
    print(f"{value:.2f}",end=" ",)

3.0 4.0 9.6 

In [11]:
# problem 3
matrix = np.array([[4, 5], [3, 2]])
det = linalg.det(matrix)
print(det)

-7.0


In [17]:
# problem 4
matrix = np.array([[5, 4],
                   [6,  3]])

eigenvalues, eigenvectors = eig(matrix)
print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[ 9.+0.j -1.+0.j]
Eigenvectors:
[[ 0.70710678 -0.5547002 ]
 [ 0.70710678  0.83205029]]


In [20]:
# problem 5
A = sparse.csr_matrix([[0, 0, 1], [1, 0, 0], [0, 2, 0]])
print("Matrix A (CSR):")
print(A)

B = sparse.csc_matrix([[5, 0, 0], [0, 0, 3], [0, 4, 0]])
print("\nMatrix B (CSC):")
print(B)

dense_A = A.toarray()
print("\nDense format of A:")
print(dense_A)

B_T = B.transpose()
print("\nTranspose of B:")
print(B_T.toarray())

product = A.dot(B)
print("\nProduct of A and B:")
print(product.toarray())
print("\nNon-zero elements in A:", A.nnz)
print("Non-zero elements in B:", B.nnz)

Matrix A (CSR):
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 2)	1
  (1, 0)	1
  (2, 1)	2

Matrix B (CSC):
<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 0)	5
  (2, 1)	4
  (1, 2)	3

Dense format of A:
[[0 0 1]
 [1 0 0]
 [0 2 0]]

Transpose of B:
[[5 0 0]
 [0 0 4]
 [0 3 0]]

Product of A and B:
[[0 4 0]
 [5 0 0]
 [0 0 6]]

Non-zero elements in A: 3
Non-zero elements in B: 3
